### ISSUE TITLE
Please provide a clear working example

### ISSUE THREAD

**Issue by jlmmns** [deployphp/action#18]
It's great to see a deployer action, but I can't get it to work.
There's also no clear indication of which repo version to use (main repo + action repo).

I almost had it working on the 6.8 version, but then the repo didn't have a proper import for Rsync.
So then I updated to "deployer/deployer": "dev-master"

Now I'm able to properly import Rsync (php), but I keep getting the following error:
`Command failed with exit code 255: vendor/bin/dep deploy develop -f ./.github/deploy.php -vvv`

This error occurs right away, when the action gets triggered.

No debug info whatsoever, regardless of the `-vvv` flag.

The deployment script has worked before, even with proper -vvv debugging.

What's going on??

**Comment by jlmmns** [comment]
Right now, I'm using "deployer/deployer": "v7.0.0-beta.24", along with the corresponding binary.

With the `./.github/deploy.yml` YAML file specified, Deployer seems to be running fine, with debugging.
But when using a `./.github/deploy.php` PHP file, the action terminates immediately with "error 255".

```
- name: Deploy
  uses: deployphp/action@master
  with:
    private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    dep: deploy develop -f ./.github/deploy.yml -vvv
```
