### ISSUE TITLE
Deployment failing

### ISSUE THREAD

**Issue by jonassiewertsen** [deployphp/action#20]
Somehow my deployment is failing and it does look like the command could not be found. 
Deployer itself has been required via composer.

![GitHub action failing](https://user-images.githubusercontent.com/38906163/129446838-74159cb6-bafe-408a-87fd-6f065bd63f94.jpg)

My workflow setup:

```yaml
name: Deploy

on:
  push:
    branches: [ zero-downtime ]
  pull_request:
    branches: [ zero-downtime ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-interaction

      - name: Deploy
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy -vvv
```
