### ISSUE TITLE
Deploy fails possibly because of wrong ssh user

### ISSUE THREAD

**Issue by hotrush** [deployphp/action#26]
My workflow steps look like this:

```
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Prepare .env
        run: echo $ENV_FILE >> ~/.env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy -vvv
```

But it couldn't deploy

```
Run deployphp/action@v1
  with:
    private-key: ***
    dep: deploy -vvv
Downloading "https://deployer.org/deployer.phar".
[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < HEAD
✈︎ Deploying HEAD on x.x.x.x
• done on [x.x.x.x]
➤ Executing task deploy:prepare
[x.x.x.x] > echo $0
[x.x.x.x] < ssh multiplexing initialization
[x.x.x.x] < Permission denied, please try again.
[x.x.x.x] < Permission denied, please try again.
[x.x.x.x] < runner@x.x.x.x: Permission denied (publickey,password).
➤ Executing task deploy:failed
• done on [x.x.x.x]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[x.x.x.x] > rm -f ~/app/.dep/deploy.lock
[x.x.x.x] < ssh multiplexing initialization
[x.x.x.x] < Permission denied, please try again.
[x.x.x.x] < Permission denied, please try again.
[x.x.x.x] < runner@x.x.x.x: Permission denied (publickey,password).

In Client.php line 103:

  [Deployer\Exception\RuntimeException (-1)]                     
  The command "rm -f ~/app/.dep/deploy.lock" failed.    

  Exit Code: -1 (Unknown error)                                  

  Host Name: x.x.x.x                                       

  ================                                               
  Permission denied, please try again.                           
  Permission denied, please try again.                           
  runner@x.x.x.x: Permission denied (publickey,password).  
```

I can see it tries to connect as `runner@x.x.x.x`, but my `deploy.php` has another user

```
host('x.x.x.x')
    ->set('remote_user', 'user')
    ->set('deploy_path', '~/{{application}}');
```

Any ideas? Thanks
