### ISSUE TITLE
Optional inputs don't work

### ISSUE THREAD

**Issue by jonnitto** [deployphp/action#3]
If I run the deploy command with optional input values, I get always the error `Too many arguments, expected arguments "command" "stage". `

If I run this command from my local machine, everything works fine.

This is my configuration
```yaml
- name: Deploy website
  uses: deployphp/action@v1.0.5
  with:
    private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    dep: deploy ${{ steps.extract-branch.outputs.branch }} --composer_auth '${{ env.composer_auth }}'
```

And this is in my PHP file:

```PHP
use Symfony\Component\Console\Input\InputOption;

option('composer_auth', null, InputOption::VALUE_OPTIONAL, 'Add a composer authentification configuration');

```

**Comment by antonmedv** [comment]
Difficult to tell what is wrong. Maybe it's some error with calling dep from nodejs:
https://github.com/deployphp/action/blob/master/index.js#L48

Also, please var_dump $argv from deploy.php file, lets print and see what the actual command is.

**Comment by jonnitto** [comment]
I think the main problem, is that the parameter contains spaces: `http-basic.domain.tld user password`. I wrote the task who uses this input to use URL decode so that I'm able to write `http-basic.domain.tld+user+password`. With this, it works. But now I can't (or at least I don't know how) replace the spaces with an `+` in the secret. (I need the secret also in another place with the spaces)

**Comment by jonnitto** [comment]
What do you mean with 

> Also, please var_dump $argv from deploy.php file, lets print and see what the actual command is.

Do you have a code example?

**Comment by jonnitto** [comment]
This is the output:
```
array(7) {
  [0] => string "bin/dep"
  [1] => string "deploy"
  [2] => string "staging"
  [3] => string "--composer_auth"
  [4] => string "'domain.tld"
  [5] => string "user"
  [6] => string"password'"
}
```
But it should be
```
array(7) {
  [0] => string "bin/dep"
  [1] => string "deploy"
  [2] => string "staging"
  [3] => string "--composer_auth"
  [4] => string "domain.tld user password"
}
```

**Comment by antonmedv** [comment]
Yes, looks like there can be a better solution with correct splitting in js code. Will implement it.

**Comment by jonnitto** [comment]
In the meantime, I was able to able to change the secret dynamically like that:

```yaml
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      composer_auth: ${{ secrets.COMPOSER_AUTH }}
    steps:
      - name: Set environment variables
        run: |
          echo "composer_auth_deployer=${composer_auth//' '/'+'}" >> $GITHUB_ENV
      # Do all the checkout, building, etc...
      - name: Deploy website
        uses: deployphp/action@v1.0.5
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          dep: deploy ${{ env.stage }} --composer_auth ${{ env.composer_auth_deployer }}
```

and in the PHP:

```php
if (input()->hasOption('composer_auth')) {
    $config = input()->getOption('composer_auth');
    if ($config) {
        cd('{{release_path}}');
        run('{{bin/composer}} config --auth ' . urldecode($config));
    }
}
```
But of course, it would be much nicer if I could use composer_auth directly.
