### ISSUE TITLE
BUG: Cannot execute two commands with Deployer Action in one workflow

### ISSUE THREAD

**Issue by lbajsarowicz** [deployphp/action#31]
## Workflow (part)
```yml
      - name: Build
        uses: deployphp/action@v1
        with:
          private-key: "${{ secrets.DEV_PRIVATE_KEY }}"
          deployer-binary: "vendor/bin/dep"
          dep: "build"
      - name: DEV environment deployment
        uses: deployphp/action@v1
        with:
          private-key: "${{ secrets.DEV_PRIVATE_KEY }}"
          deployer-binary: "vendor/bin/dep"
          dep: "deploy-artifact develop"
```

## Result

![image](https://user-images.githubusercontent.com/1639941/158067506-235ab9d5-7c1c-44d4-b4f9-647f3295c4bf.png)

**Comment by jamsch** [comment]
Just encountered this as well. It's currently not possible to cancel the workflow while Deployer is running, because it adds a `.lock` file on the host OS. I thought that adding another Deployer step to run the unlock, but had the same issue as above.

```yaml
      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_FORGE_PRIVATE_KEY }}
          dep: deploy stage=staging -v --branch=${{ github.ref_name }}
      - name: Unlock deploy if job was cancelled
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy:unlock stage=staging -v
        if: cancelled()
```
