### ISSUE TITLE
Action connecting to server with wrong user

### ISSUE THREAD

**Issue by ortzinator** [deployphp/action#43]
Here's the output. As you can see, it's trying to connect with the user `runner`. I assume this is the local user for github actions but as you can see below, I set `remote_user` to `jamar` so I'm not sure why that's being ignored.

```
Run deployphp/action@v1.0.17
Downloading "https://deployer.org/deployer.phar".
[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < master
✈︎ Deploying master on 96.30.197.133
• done on [96.30.197.133]
➤ Executing task deploy:prepare
[96.30.197.133] > echo $0
[96.30.197.133] < ssh multiplexing initialization
[96.30.197.133] < runner@96.30.197.133: Permission denied (publickey).
➤ Executing task deploy:failed
• done on [96.30.197.133]
✔ Ok [0ms]
➤ Executing task deploy:unlock
[96.30.197.133] > rm -f /var/www/sites/jamar/.dep/deploy.lock
[96.30.197.133] < ssh multiplexing initialization
[96.30.197.133] < runner@96.30.197.133: Permission denied (publickey).

In Client.php line 103:
                                                                     
  [Deployer\Exception\RuntimeException (-1)]                         
  The command "rm -f /var/www/sites/jamar/.dep/deploy.lock" failed.  
                                                                     
  Exit Code: -1 (Unknown error)                                      
                                                                     
  Host Name: 96.30.197.133                                           
                                                                     
  ================                                                   
  runner@96.30.197.133: Permission denied (publickey).               
                                                                     

Exception trace:
  at phar:///home/runner/work/jamar/jamar/deployer.phar/src/Ssh/Client.php:103
 Deployer\Ssh\Client->run() at phar:///home/runner/work/jamar/jamar/deployer.phar/src/functions.php:304
 Deployer\run() at phar:///home/runner/work/jamar/jamar/deployer.phar/recipe/deploy/lock.php:30
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///home/runner/work/jamar/jamar/deployer.phar/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///home/runner/work/jamar/jamar/deployer.phar/src/Executor/SeriesExecutor.php:60
 Deployer\Executor\SeriesExecutor->run() at phar:///home/runner/work/jamar/jamar/deployer.phar/src/Console/TaskCommand.php:157
 Deployer\Console\TaskCommand->execute() at phar:///home/runner/work/jamar/jamar/deployer.phar/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///home/runner/work/jamar/jamar/deployer.phar/vendor/symfony/console/Application.php:924
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/runner/work/jamar/jamar/deployer.phar/src/Console/Application.php:133
 Deployer\Console\Application->doRunCommand() at phar:///home/runner/work/jamar/jamar/deployer.phar/vendor/symfony/console/Application.php:265
 Symfony\Component\Console\Application->doRun() at phar:///home/runner/work/jamar/jamar/deployer.phar/vendor/symfony/console/Application.php:141
 Symfony\Component\Console\Application->run() at phar:///home/runner/work/jamar/jamar/deployer.phar/src/Deployer.php:326
 Deployer\Deployer::run() at phar:///home/runner/work/jamar/jamar/deployer.phar/bin/dep:136
 require() at /home/runner/work/jamar/jamar/deployer.phar:4

deploy [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

Error: Failed: dep deploy -vvv
```

```php
//deploy.php
<?php
namespace Deployer;

require 'recipe/laravel.php';

// Config

set('repository', 'git@github.com:ortzinator/jamar.git');

add('shared_files', ['.env']);
add('shared_dirs', ['storage']);
add('writable_dirs', ['storage']);

// Hosts

host('96.30.197.133')
    ->set('remote_user', 'jamar')
    ->set('deploy_path', '/var/www/sites/jamar');

// Tasks

task('build', function () {
    cd('{{release_path}}');
    run('npm run build');
});

after('deploy:failed', 'deploy:unlock');
```

```yaml
#deploy.yml
name: deploy

on:
  push:
    branches: [master]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"

      - name: Deploy
        uses: deployphp/action@v1.0.17
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy -vvv
```
