### ISSUE TITLE
Cannot set `deployer-version`

### ISSUE THREAD

**Issue by benjaminmal** [deployphp/action#46]
When setting the `deployer-version` parameter to try to find a workaround of #45, an error occured. It seems the action can't download other versions than the default one.

Here is the error:

![Capture d’écran 2022-09-08 à 15 05 34](https://user-images.githubusercontent.com/58468686/189130001-d951a547-c0d7-4e89-85a4-46d55998cd12.png)

**Comment by benjaminmal** [comment]
See https://github.com/deployphp/action/issues/45#issuecomment-1240729167 for a workaround

**Comment by ToshY** [comment]
Using with quotes works fine:

```yaml
      - name: Deploy
        uses: deployphp/action@v1
        with:
          deployer-version: "7.0.2"
```
