### ISSUE TITLE
`private-key` property shouldn't be required

### ISSUE THREAD

**Issue by benjaminmal** [deployphp/action#47]
When I test my deploy in my CI, I deploy my project locally. `private-key` is not needed here, but is required by the action. So I think it should not be required :) 

```yaml
            -  name: Test deploy
                uses: deployphp/action@v1
                with:
                    dep: deploy localhost -o deploy_path="~/deploy-test"
```

![Capture d’écran 2022-09-19 à 16 31 12](https://user-images.githubusercontent.com/58468686/191042338-dd198c03-147b-42e6-a1cb-7d42df787f22.png)
