### ISSUE TITLE
How to set directory where deploy has to be made

### ISSUE THREAD

**Issue by knewitzgui** [deployphp/action#57]
im trying to create a deploy workflow but i need to deploy the application on a subdomain, how i set the directory of the server where the deploy need to be made?
Already tried working-directory and run a cd in the path that i need, nothing worked.

![image](https://user-images.githubusercontent.com/49166923/212211459-049bfa5c-5922-46e9-a7a1-4d65a16c169c.png)

**Comment by benjaminmal** [comment]
You have to set up a [`deploy_path`](https://deployer.org/docs/7.x/recipe/common#deploy_path) like this:

```yaml
            -   name: Test deploy
                uses: deployphp/action@v1
                with:
                    dep: deploy localhost -o deploy_path=my_deploy_path/deploy-test
                    private-key: ${{ secrets.HOST_SSH_KEY }}
```

With a new `localhost` host:
```yaml
# deploy.yaml

hosts:
    localhost:
        local: true
```
