### ISSUE TITLE
Bug: verbosity level option doesn't work

### ISSUE THREAD

**Issue by vitalykarasik** [deployphp/action#66]
I tried to increase verbosity level using both "-vv" and "-vvv" options, but the log I still see "php deployer.phar deploy altius-demo --no-interaction --ansi -v " command, and no debug output.

```
uses: deployphp/action@v1
        with:
          deployer-version: "6.8.0"
          dep: deploy demo
          private-key: ${{ secrets.SSH_DEPLOY_KEY }}
          ssh-config: ${{ vars.SSH_CONFIG_DEPLOYER }}
          options: |
            branch: $DEPLOY_BRANCH
            keep_releases: 10
            verbosity: -vvv
```
