### ISSUE TITLE
`options` is not working

### ISSUE THREAD

**Issue by Seb33300** [deployphp/action#72]
The `options` input provided in the README is not working:

```yaml
  - name: Deploy
    uses: deployphp/action@v1
    with:

      # Config options for the Deployer. Same as the `-o` flag in the CLI.
      # Optional.
      options:
        keep_releases: 7
```

When trying to use it, i have a syntax error message.

I also tried this syntax: no error, but options are ignored.
 
```yaml
      options: |
        keep_releases: 7
```

**Comment by Seb33300** [comment]
If this can help, a workaround for this is to use the `dep` and pass options to the command line:

```yaml
  - uses: deployphp/action@v1
    with:
    dep: deploy uat -o branch=main -o keep_releases=3
```
