### ISSUE TITLE
Command "deploy" is not defined.

### ISSUE THREAD

**Issue by tobz-nz** [deployphp/action#84]
I'm getting this error

```
Run deployphp/action@v1
  
$ ssh-agent -a /tmp/ssh-auth.sock
SSH_AUTH_SOCK=/tmp/ssh-auth.sock; export SSH_AUTH_SOCK;
SSH_AGENT_PID=2514; export SSH_AGENT_PID;
echo Agent pid 2514;
$ ssh-add -
Identity added: (stdin) (action@deployer.org)
Using "vendor/bin/dep".
$ php vendor/bin/dep deploy main -o keep_releases=3  --no-interaction --ansi -v 
In Application.php line 720:
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "deploy" is not defined.                                
                                                                  
Exception trace:
  at phar:///home/runner/work/project/project/vendor/deployer/deployer/dep/vendor/symfony/console/Application.php:720
 Symfony\Component\Console\Application->find() at phar:///home/runner/work/project/project/vendor/deployer/deployer/dep/vendor/symfony/console/Application.php:259
 Symfony\Component\Console\Application->doRun() at phar:///home/runner/work/project/project/vendor/deployer/deployer/dep/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///home/runner/work/project/project/vendor/deployer/deployer/dep/src/Deployer.php:317
 Deployer\Deployer::run() at phar:///home/runner/work/project/project/vendor/deployer/deployer/dep/bin/dep:96
 require() at /home/runner/work/project/project/vendor/deployer/deployer/dep:4
 include() at /home/runner/work/project/project/vendor/bin/dep:119
Error: Failed: dep deploy,main,-o,keep_releases=3
```

This is my `deploy` workflow step. Everything works up until here.

```yml
  deploy:
    needs: [tests]
    concurrency: production_environment
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && (endsWith(github.ref, '/main') || endsWith(github.ref, '/staging'))

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Add Composer HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install dependencies
        run: composer install

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.PRIVATE_KEY }}
          dep: deploy ${{ github.head_ref || github.ref_name }} -o keep_releases=3
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/action/issues/84">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/action/issues/84/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/action/issues/84/pledge.svg">
</picture>
</a>
